version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  user-service:
    build:
      context: ./user-service
    ports:
      - "50051:50051"
    depends_on:
      - postgres
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=mydb
      - DB_HOST=postgres
    command: ["./main"]

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service

volumes:
  pgdata:
